$wp_219 = ~/Bilder/Wallpaper/Lotus Emira GT4/2023-Lotus-Emira-GT4-002-1440w.jpg
$wp_916 = ~/Bilder/Wallpaper/Mobile/ELECTRIFIED MOBILE WALLPAPER.jpg

# --- SPLASH    ---
splash = true

# --- PRELOAD   ---
preload = $wp_219
preload = $wp_916

# --- WALLPAPER ---
wallpaper = DP-2,$wp_219
wallpaper = DP-3,$wp_916
