## --- GENERAL ---
splash = false
ipc = false

## --- WALLPAPER ---
wallpaper {
  monitor = DP-2
  path = ~/Bilder/Wallpaper/rose-pine/min-arch.jpg
  fit_mode = cover
#  timeout = 300
}
wallpaper {
  monitor = DP-3
  path = ~/Bilder/Wallpaper/Hyprland/wall2.png
  fit_mode = cover
#  timeout = 300
}
