## --- GENERAL ---
splash = false
ipc = false

## --- WALLPAPER ---
wallpaper {
  monitor = DP-2
#  path = ~/Bilder/Wallpaper/KDE/Skyscraper/contents/images/3840x2160.png
  path = ~/Bilder/Wallpaper/Panda/panda-wallpapers-that-are-as-cool-as-your-phone-free-photo.jpg
  fit_mode = cover
#  timeout = 300
}
wallpaper {
  monitor = DP-3
  path = ~/Bilder/Wallpaper/Hyprland/wall2.png
  fit_mode = cover
#  timeout = 300
}
