# BEGIN_KITTY_THEME
# Catppuccin-Frappe
include current-theme.conf
# END_KITTY_THEME

# fonts
font_family family='0xProto Nerd Font' style=Regular features=+calt
#font_family CodeNewRomanNF
#font_family family='BlexMono Nerd Font' style=Text features='+zero +ss01 +ss02'
#font_family family='CommitMono Nerd Font' features=+calt
#font_family family='D2CodingLigature Nerd Font' features=+calt
#font_family family='FantasqueSansM Nerd Font' features=+calt
#font_family family='GeistMono Nerd Font' style=Medium features='+liga +ss08 +ss03 +ss04'
#font_family  family='JetBrainsMono Nerd Font' style=Regular features='+zero cv08=8 cv02=2 cv04=4 cv06=6 cv11=11 cv12=12 cv14=14 cv16=16 cv17=17 cv18=18 cv19=19 cv20=20'
#font_family family='IosevkaTermSlab Nerd Font' style=Medium features='+calt +zero'
#font_family family='Lekton Nerd Font' style=Regular features=+smcp
#font_family LilexNerdFont
#font_family family='MartianMono Nerd Font' features='+calt'
#font_family MonaspiceNeNerdFont
#font_family RecMonoDuotoneNerdFont
#font_family family='ZedMono Nerd Font' style=Medium features='+calt +dlig +frac +lnum'
bold_font auto
italic_font auto
bold_italic_font auto
disable_ligatures never
font_size 20

## cursor settings
# cursor #f38b0e
cursor #00b5da
cursor_text_color #111111
cursor_shape block
cursor_shape_unfocused hollow

# scrollback
scrollback_lines 42000
scrollback_indicator_opacity 0.5

# mouse
mouse_hide_wait 1.25
copy_on_select clipboard
strip_trailing_spaces smart

# color scheme
background_opacity 0.75

# terminal bell # https://sw.kovidgoyal.net/kitty/conf/#terminal-bell
enable_audio_bell no
visual_bell_duration 0.3
visual_bell_color rgb:78/90/9c

