# BEGIN_KITTY_THEME
# Catppuccin-Frappe
include current-theme.conf
# END_KITTY_THEME

# fonts
#font_family 0xProtoNerdFont
#font_family CodeNewRomanNF
#font_family CommitMonoNerdFont
#font_family D2CodingLigatureNerdFont
#font_family FantasqueSansMNerdFont
#font_family GeistMonoNerdFont
#font_family IosevkaTermNerdFont
font_family IosevkaTermSlabNerdFont
#font_family LilexNerdFont
#font_family RecMonoCasualNerdFont
#font_family RecMonoDuotoneNerdFont
bold_font auto
italic_font auto
bold_italic_font auto
disable_ligatures never
font_size 18

# cursor
cursor_shape block
cursor_shape_unfocused hollow

# scrollback
scrollback_lines 42000
scrollback_indicator_opacity 0.5

# mouse
mouse_hide_wait 1.25
copy_on_select clipboard
strip_trailing_spaces smart

# color scheme
background_opacity 0.75

# terminal bell # https://sw.kovidgoyal.net/kitty/conf/#terminal-bell
enable_audio_bell no
visual_bell_duration 0.3
visual_bell_color rgb:78/90/9c

