return {
	"nvim-treesitter/nvim-treesitter",
	lazy = false,
	event = { "BufReadPre", "BufNewFile" },
	branch = "main",
	build = ":TSUpdate",
	dependencies = {
		"windwp/nvim-ts-autotag",
	},
	config = function()
		-- import nvim-treesitter plugin
		local treesitter = require("nvim-treesitter")

		-- pre-installed language parsers
		treesitter.install({
			"angular",
			"arduino",
			"bash",
			"bibtex",
			"c",
			"c_sharp",
			"cpp",
			"css",
			"devicetree",
			"dockerfile",
			"gdscript",
			"gitignore",
			"gpg",
			"graphql",
			"fish",
			"html",
			"javascript",
			"json",
			"kotlin",
			"latex",
			"lua",
			"markdown",
			"markdown_inline",
			"passwd",
			"php",
			"powershell",
			"prisma",
			"python",
			"query",
			"regex",
			"rust",
			"sql",
			"ssh_config",
			"svelte",
			"tsx",
			"typescript",
			"vim",
			"vimdoc",
			"yaml",
		})
	end,
}
